# Generated by Django 5.0.4 on 2024-05-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_remove_quiz_file_remove_quiz_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.course'),
        ),
    ]
