# Generated by Django 5.0.4 on 2024-05-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.course'),
        ),
    ]
