# Generated by Django 5.0.4 on 2024-05-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_quiz_course_remove_quiz_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
