# Generated by Django 5.0.4 on 2024-05-19 13:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_assignment_course_remove_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(default='default/path/to/file.pdf', upload_to='course_assignments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 19, 13, 39, 42, 914761, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(default='default/path/to/file.pdf', upload_to='course_quizzes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 19, 13, 44, 7, 624810, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
