# Generated by Django 5.0.4 on 2024-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_assignment_course_assignment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_details', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payout_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
