# Generated by Django 5.0.4 on 2024-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresult',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
